apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  selector:
    app: file-upload-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
